export const EXAM_PRESETS: Record<string, string[]> = {
  'CBSE Class 10': [
    'Number systems',
    'Algebra',
    'Coordinate geometry',
    'Geometry',
    'Trigonometry',
    'Mensuration',
    'Statistics and probability',
  ],
  'CBSE Class 12 Science': [
    'Electrostatics',
    'Current electricity',
    'Magnetic effects',
    'Electromagnetic induction',
    'Optics',
    'Modern physics',
  ],
  'CBSE Class 12 Commerce': [
    'Financial statements',
    'Accounting ratios',
    'Cash flow',
    'Partnership',
    'Company accounts',
  ],
  'JEE Mains Physics': ['Mechanics', 'Thermodynamics', 'Waves', 'Electricity', 'Magnetism', 'Optics', 'Modern physics'],
  'JEE Mains Chemistry': ['Physical chemistry', 'Organic chemistry', 'Inorganic chemistry'],
  'JEE Mains Maths': ['Algebra', 'Calculus', 'Coordinate geometry', 'Trigonometry', 'Probability'],
  'NEET Biology': ['Cell biology', 'Genetics', 'Plant physiology', 'Human physiology', 'Ecology', 'Evolution'],
  'NEET Physics': ['Mechanics', 'Thermodynamics', 'Optics', 'Modern physics', 'Electromagnetism'],
  'NEET Chemistry': ['Organic', 'Inorganic', 'Physical'],
  'GATE CSE': ['DSA', 'Algorithms', 'OS', 'DBMS', 'CN', 'TOC', 'Compiler design'],
  Custom: [],
};
